[[main]]
name = "Home"
url = ""
weight = 1

# [[main]]
# name = "Element"
# url = "element/"
# weight = 4


[[main]]
weight = 2
name = "News"
hasChildren = true

[[main]]
parent = "News"
name = "Latest News"
url = "/news"

[[main]]
parent = "News"
name = "Events"
url = "/events"

# [[main]]
# parent = "News"
# name = "Categories"
# url = "/categories"

[[main]]
weight = 3
name = "Advocacies"
url = "/advocacies"


[[main]]
weight = 4
name = "About"
hasChildren = true

[[main]]
parent = "About"
name = "About Us"
url = "/about"

[[main]]
parent = "About"
name = "Contact"
url = "/contact"
